version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./config/server_config.ini:/config.ini
      - ./config/bets.csv:/bets.csv
      - ./layer/message_protocol.py:/common/message_protocol.py
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
    volumes:
      - ./config/client_config.ini:/config.ini
      - ./.data/agency-1.csv:/bets.csv
      - ./layer/message_protocol.py:/common/message_protocol.py
    networks:
      - testing_net
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=DEBUG
    volumes:
      - ./config/client_config.ini:/config.ini
      - ./.data/agency-2.csv:/bets.csv
      - ./layer/message_protocol.py:/common/message_protocol.py
    networks:
      - testing_net
    depends_on:
      - server

  client3:
    container_name: client3
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=3
      - CLI_LOG_LEVEL=DEBUG
    volumes:
      - ./config/client_config.ini:/config.ini
      - ./.data/agency-3.csv:/bets.csv
      - ./layer/message_protocol.py:/common/message_protocol.py
    networks:
      - testing_net
    depends_on:
      - server

  client4:
    container_name: client4
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=4
      - CLI_LOG_LEVEL=DEBUG
    volumes:
      - ./config/client_config.ini:/config.ini
      - ./.data/agency-4.csv:/bets.csv
      - ./layer/message_protocol.py:/common/message_protocol.py
    networks:
      - testing_net
    depends_on:
      - server

  client5:
    container_name: client5
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=5
      - CLI_LOG_LEVEL=DEBUG
    volumes:
      - ./config/client_config.ini:/config.ini
      - ./.data/agency-5.csv:/bets.csv
      - ./layer/message_protocol.py:/common/message_protocol.py
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
